### PR TITLE
DolphinQt/ScriptingWidget: Switch to QTreeView

### PR DESCRIPTION
**Pull request by malleoz**
This gives us a better list of all scripts available to the user. It also updates in real-time.

- Double-click or click checkbox to toggle script
- Double-click or click arrow next to folder to expand directory
- "+" button now copies the chosen script to the script folder
- refresh button still behaves as normal
- refactor global script list to only contain the currently running scripts
- ISSUE: subfolders with no files or non-Python files still appear :(

### CODE REVIEW

**Review by ximk — DISMISSED** [review]
Scripts that were previously able to automatically run on launch using the `_` prefix no longer auto-run.

**Comment by malleoz** [comment]
Good catch, will update this later today

**Review by ximk — APPROVED** [review]

**Review by ximk — CHANGES_REQUESTED** [review]
Missed some things with my initial testing (these apply when Dolphin is running while doing these actions):

- Auto-run scripts are toggled off when moved into another folder.
- Moving a script into a folder "unchecks" it, but does not actually shut down the script.

**Comment by malleoz** [comment]
> * Auto-run scripts are toggled off when moved into another folder.
> * Moving a script into a folder "unchecks" it, but does not actually shut down the script.
They're essentially treated as new files because the path is different. And there's apparently no easy way to react to the file being moved or deleted using a `QFileSystemModel`. I think we're going to have to live with this behavior if we want these changes. This is an unlikely scenario for the user to encounter.

**Comment by ximk** [comment]
> I think we're going to have to live with this behavior if we want these changes. This is an unlikely scenario for the user to encounter.
Agreed, reapproving.

**Review by ximk — APPROVED** [review]

**Pull request merged**
