### PR TITLE
Add linux build directions

### PR DESCRIPTION
**Pull request by saltq144**

### CODE REVIEW

**Comment by Gaberboo** [comment]
This is obviously specific to your system, it is not necessary on mine

**Comment by saltq144** [comment]
What version of g++ do you use?

I did replicate the relevant error on an old laptop 441 upgrades behind. I wouldn't call this system specific.

Annoyingly, the latest version of g++ ubuntu ships is 11.4.0 which does have this error.

**Comment by malleoz** [comment]
Sorry as I don't use linux, but can I get further clarification on whether these instructions would apply to the majority of users, or if these really are system-specific instructions.

**Comment by Gaberboo** [comment]
They are specific to his system that I'm pretty sure is missing the libstdc++ runtime libraries.

**Comment by saltq144** [comment]
Again, what does `c++ --version` produce on your machine?

Manually setting which compiler CMake uses is needed, because CMake first looks for the c++ command, which a manual build and install of gcc does not set, but your package manager almost certainly does.

Setting static libstdc++ means that the user does not have to set LD_LIBRARY_PATH and can safely remove the manually installed gcc.

I will note that the c++ command can be configured to the manually installed g++ version, although I do not think that is appropriate for build directions.

I will also note that setting LD_LIBRARY_PATH to /usr/local/lib64 does avoid static libstdc++, but as I said earlier that prevents uninstalling the manually installed g++.

Also, rewriting DecrefPyObjectsInArgs (in Source/Core/Scripting/Python/Modules/eventmodule.cpp) to not trigger a compiler bug in what AFAIK is the **most common distro** will also solve the problem and reduce total build time by over 2 hours on some systems.

**Comment by saltq144** [comment]
Again, what does `c++ --version` produce on your machine?

Manually setting which compiler CMake uses is needed, because CMake first looks for the c++ command, which a manual build and install of gcc does not set, but your package manager almost certainly does.

Setting static libstdc++ means that the user does not have to set LD_LIBRARY_PATH and can safely remove the manually installed gcc.

I will note that the c++ command can be configured to the manually installed g++ version, although I do not think that is appropriate for build directions.

I will also note that setting LD_LIBRARY_PATH to /usr/local/lib64 does avoid static libstdc++, but as I said earlier that prevents uninstalling the manually installed g++.

Also, rewriting DecrefPyObjectsInArgs (in Source/Core/Scripting/Python/Modules/eventmodule.cpp) to not trigger a compiler bug in what AFAIK is the **most common distro** will also solve the problem and reduce total build time by over 2 hours on some systems.

**Comment by Gaberboo** [comment]
Problem, I do not care about the ways you hacked around your perceived deficiencies in the most popular distro for what is by far the least popular competitive desktop OS, I care about build instructions that are best for normal unmangled systems

**Comment by saltq144** [comment]
Can you stop avoiding the question, and take 3 seconds to see if you have already done the steps. Run `c++ --version` and say what it shows.

**Pull request closed without merging**
